### ISSUE TITLE
Installation from Docker Hub not working as documented

### ISSUE THREAD

**Issue by jtwolgamott** [smart-on-fhir/fhir-viewer#1]
If I run the documented `docker run -p 9090:80 vladignatov/fhir-viewer:latest`, I receive the following error message (even after logging into Docker Hub):

```
Unable to find image 'vladignatov/fhir-viewer:latest' locally
docker: Error response from daemon: pull access denied for vladignatov/fhir-viewer, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

I searched Docker Hub and this image is nowhere to be found. However, I did find and image named smartonfhir/fhir-viewer, which appears to be the correct image. Is it possible that this documentation simply needs to be updated to reflect the correct image name?

**Comment by vlad-ignatov** [comment]
That is exactly the case. Thank you for pointing this out. The documentation is now updated.
